name: excerpt
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path: ^1.9.0
  google_fonts: ^6.2.1
  pdf: ^3.11.1
  printing: ^5.13.1
  image_picker: ^1.1.2
  archive: ^3.6.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/ExcerptLogoHQ.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true